# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppPOMPP <- function(beta, delta, lambda, b_updater, d_updater, l_updater, parB, parD, lambdaA, lambdaB, covsClass, covariates, areaD, xClass, mu, nugget, marksMuMu, marksMuS2, marksNuggetA, marksNuggetB, xValues, xMarks, xPositions, intensityCovs, observabilityCovs, xIntensityCovs, xObservabilityCovs, maxDist, sigma2, phi, neighborhoodSize, longCol, latCol, burnin, thin, iter, threads, verbose) {
    .Call(`_pompp_cppPOMPP`, beta, delta, lambda, b_updater, d_updater, l_updater, parB, parD, lambdaA, lambdaB, covsClass, covariates, areaD, xClass, mu, nugget, marksMuMu, marksMuS2, marksNuggetA, marksNuggetB, xValues, xMarks, xPositions, intensityCovs, observabilityCovs, xIntensityCovs, xObservabilityCovs, maxDist, sigma2, phi, neighborhoodSize, longCol, latCol, burnin, thin, iter, threads, verbose)
}

